services:
  db-didi-students:
    image: postgres
    container_name: db-postgres-didi-students
    restart: always
    ports: [1234:5432]
    env_file:
      - ./back-end/.env
    volumes:
      - didi-students:/var/lib/postgresql/data
  
  back-end:
    container_name: node-app-didi-students
    build: ./back-end
    ports:
      - "81:5000"
    depends_on:
      - db-didi-students
    env_file:
      - ./back-end/.env

volumes:
  didi-students:
