services:
  db-didi-students:
    image: postgres
    container_name: db-postgres-didi-students
    restart: always
    ports: [1234:5432]
    env_file:
      - back-end/.env
    volumes:
      - didi-students:/var/lib/postgresql/data
  
  back-end:
    container_name: node-app-didi-students
    build: ./back-end
    image: node-app-didi-students_image
    ports:
      - 5000:5000
    depends_on:
      - db-didi-students
    env_file:
      - back-end/.env

  front-end:
    container_name: react-didi-students
    build: ./front-end
    image: react-didi-students_image
    volumes:
      - build_react:/var/www/html

  nginx:
    container_name: nginx-didi-students
    build: ./nginx
    image: nginx-didi-students_image
    ports:
      - 80:80
    volumes:
      - build_react:/var/www/html
    depends_on:
      - db-didi-students
      - back-end
      - front-end

volumes:
  didi-students:
  build_react:
