on: 
  push:
    branches:
      - main

name: Build & Deploy
jobs:
  build:
    runs-on: self-hoted
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Create back-end env file
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_POSTGRES_USER: ${{secrets.POSTGRES_USER}}
          envkey_POSTGRES_PASSWORD: ${{secrets.POSTGRES_PASSWORD}}
          envkey_POSTGRES_BD: ${{secrets.POSTGRES_DB}}
          envkey_DATABASE_URL: ${{secrets.DATABASE_URL}}
          directory: back-end
          file-name: .env
          fail_on_empty: true
      
      - name: Create front-env env file
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_REACT_APP_BASR_URL: ${{secrets.REACT_APP_BASR_URL}}
          directory: front-end/
          file_name: .env
          fail_on_empty: true

      - name: Build
        run: docker-compose build

      - name: Run
        run: docker-compose down && docker-compose up -d